version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'juma-mysql'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3333:3306"

volumes:
  mysqldata: