version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'juma-mysql'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3333:3306"
  redis:
    image: redis
    container_name: juma-redis
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
    container_name: juma-backend
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - redis
    volumes:
      - /app/node_modules
      - .:/app
volumes:
  mysqldata: